### PR TITLE
Add deepl-node to project

### PR DESCRIPTION
**Pull request by shaimole**
## Intention
A friend of mine needed mass-translation of an entire database file for his game. I did this manually using the deepl API, but i think it would be an awesome feature to have in an actual module (I think there is an open issue aswell). I found yours is quite good, but it's missing the feature to translate multiple entities at once.
Such a feature is certainly possible but i ran into limitations with the 500k character limit of deepl-free.

## Why use [deepl-node](https://www.npmjs.com/package/deepl-node)
- automatic compatibility to current deepl API Version via npm update
- out of the box extended API features such as [Usage](https://github.com/DeepLcom/deepl-node/blob/main/src/index.ts#L493) 
- glossary support
- easy error handling
- ...

I hope we can talk about this being feasible and work together to improve fvtt for the community

### CODE REVIEW

**Comment by Meneltamar** [comment]
Just adding DeepL Node to the project won't really help. It is still a frontend module and the package functions would need to be exposed in the frontend. I tried implementing DeepL Node earlier but ran into issues with webpack when transpiling some of the functions in DeepL Node.

Mass translations are possible without DeepL Node, and I have thought about implementing them but haven't gotten around to it yet. Again, I would expose this functionality in the frontend via i.e. a button for a JournalEntry Folder that would translate all journals in that folder.

DeepL Node also won't change the issue with the 500k character limit. Are you using a Pro subscription? If yes, the only thing that would need to be implemented is a switch for the URL that gets called based on whether the token supplied is a Pro or Free token.

**Comment by shaimole** [comment]
Thank you for your quick reply.
I don't know that much about fvtt but if this module is frontend only i makes sense you haven't used deepl-node yet.
I don't use a pro subscription but in the scope of mass translations a user could easily exceed his quota. 
The program  could count the character which are going to be translated and compare against the remaining deepl free volume. This way the user would know beforehand how much of the notes can be translated this month and choose wisely.
Also the user could keep track of his remaining deepl budget this way.

What about a version for the dedicated server only? I think in most cases the dm will prepare a game and translates the notes beforehand. Is this a possibility?

**Comment by shaimole** [comment]
Also this way content creators could translate and publish their journals for the community in multiple languages.

**Comment by Meneltamar** [comment]
Few thoughts on this:

Even GMs do not ever directly interface with the Server/NodeJS side of FoundryVTT (other than to star the server up). Everything the GM does is done through the client-side browser frontend (logged in as a GM with elevated privileges). In fact, it is HIGHLY discouraged to start manually editing database files because it runs the risk of corrupting your worlds.

I will not (and cannot) support publication of journals from within the module. This is a copyrights issue when people translate texts under copyright. Nothing keeps people from doing this right now (Foundry already allows exporting every single item as an easily shareable JSON).

In my experience, someone running a weekly game will most likely not exceed their monthly quota if they only translate what they need (and maybe a bit more). The available quota can easily be checked on the DeepL website. Checking the available quota before mass-translation is a neat idea and I will think about it when and if I get around to implementing mass translations.

**Comment by shaimole** [comment]
Alright I feel free to close this PR.
Thank you for your time and insights of how these modules interface with the fvvt base. 
I agree, that the database files should not be edited manually.
I was not suggesting this code to do the publishing, more to be it a neat tool for DMS to convert their campaigns and publish themself afterwards.

For your future implementation of mass translation here a my insights from my translation task last night:

- translating about 300 objects (only descriptions) took about 60% of the free quota
- I saw you already noticed this, but different objects have different keys which need to translated (e.g. description.value, name, components...) I would be great to have the ability to choose which fields of any set should be translated, prolly via a small dialog which displays the available fields
- fvvt has an i18n module, is it feasible to use this module instead of creating new objects?

Have a nice weekend

**Comment by Meneltamar** [comment]
I haven't looked deeply into the i18n stuff. My understanding is, though, that this would require the initial journals to already contain only i18n references to the text that is then stored in a localization file. Then you simply add an additional localization file that maps the i18n keys to the respective translated text. So this also doesn't really apply for the use-case that I have in mind for this module.

Concerning the different keys: This is an unfortunate side-effect of how many systems define their own data models for stuff, so it is almost impossible to think of every single case a priori without actually looking into the data structures of every single system out there. 

If someone gives me a ping, whenever they encounter an entity in a system where the module doesn't know the right attribute yet, together with a description where in the respective data models description is, I can easily implement it over time. The system I run and play, however, works with the standard item.description.

**Pull request closed without merging**
